In [15]:
import matplotlib.pyplot as plt

from sklearn import datasets, metrics
from sklearn.model_selection import train_test_split

digits = datasets.load_digits()
n_samples = len(digits.images)
data = digits.images.reshape((n_samples, -1))

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=6)

X_train, X_test, y_train, y_test = train_test_split(
    data, digits.target, test_size=0.2)

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [20]:
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.8416666666666667
[[32  0  0  0  0  1  0  0  0  0]
 [ 0 24  0  0  2  2  1  1  2  2]
 [ 1  0 32  1  0  0  0  0  4  0]
 [ 0  1  0 28  0  1  0  0  4  2]
 [ 0  0  0  0 34  1  0  3  1  2]
 [ 0  0  0  2  0 39  0  0  2  1]
 [ 0  0  0  0  1  1 41  0  2  0]
 [ 0  1  0  1  0  3  0 23  0  0]
 [ 0  2  2  1  1  0  0  0 23  0]
 [ 0  0  1  2  0  1  0  0  1 27]]


In [21]:
# Build a logistic regression classifier and predict

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.975
[[33  0  0  0  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  0  0  0  0]
 [ 0  0 38  0  0  0  0  0  0  0]
 [ 0  0  0 35  0  0  0  0  0  1]
 [ 0  1  0  0 39  0  0  0  0  1]
 [ 0  1  0  0  0 42  0  0  0  1]
 [ 0  0  0  0  0  0 45  0  0  0]
 [ 0  0  0  0  0  0  0 28  0  0]
 [ 0  2  0  0  0  0  0  0 26  1]
 [ 0  0  0  0  0  1  0  0  0 31]]


C:\Users\7kingdom\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [22]:
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.9805555555555555
[[33  0  0  0  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  0  0  0  0]
 [ 0  0 38  0  0  0  0  0  0  0]
 [ 1  0  0 35  0  0  0  0  0  0]
 [ 0  0  0  0 40  0  0  1  0  0]
 [ 0  0  0  0  0 44  0  0  0  0]
 [ 1  0  0  0  0  0 44  0  0  0]
 [ 0  0  0  0  0  0  0 28  0  0]
 [ 0  2  1  0  0  0  0  0 26  0]
 [ 0  0  0  0  0  1  0  0  0 31]]


In [23]:
from sklearn.neighbors import KNeighborsClassifier

# 대충 k값 5
clf_knn = KNeighborsClassifier(n_neighbors=5)  # You can adjust the number of neighbors (k) as needed
clf_knn.fit(X_train, y_train)

pred_knn = clf_knn.predict(X_test)

print("\n--- K-Nearest Neighbors (KNN) Classifier ---")
print("Accuracy:", accuracy_score(y_test, pred_knn))
print("Confusion Matrix:")
print(confusion_matrix(y_test, pred_knn))



--- K-Nearest Neighbors (KNN) Classifier ---
Accuracy: 0.9888888888888889
Confusion Matrix:
[[33  0  0  0  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  0  0  0  0]
 [ 0  0 38  0  0  0  0  0  0  0]
 [ 0  0  0 35  0  0  0  0  0  1]
 [ 0  0  0  0 41  0  0  0  0  0]
 [ 0  0  0  0  0 44  0  0  0  0]
 [ 0  0  0  0  0  0 45  0  0  0]
 [ 0  0  0  0  0  0  0 28  0  0]
 [ 0  2  0  1  0  0  0  0 26  0]
 [ 0  0  0  0  0  0  0  0  0 32]]
