In [2]:
import numpy as np

import pandas as pd

import seaborn as sns


In [6]:
file_path = 'C:/Users/7kingdom/Documents/인공지능개론/src/iris/iris.data'

#class = Iris Setosa, Iris Versicolour, Iris Virginica
column_names = ["sepal length in cm", "sepal width in cm", "petal length in cm", "petal width in cm", "class"]          

df = pd.read_csv(file_path, header=None, names=column_names)

df.head(10)

sepal length in cm  sepal width in cm  petal length in cm  \
0                 5.1                3.5                 1.4   
1                 4.9                3.0                 1.4   
2                 4.7                3.2                 1.3   
3                 4.6                3.1                 1.5   
4                 5.0                3.6                 1.4   
5                 5.4                3.9                 1.7   
6                 4.6                3.4                 1.4   
7                 5.0                3.4                 1.5   
8                 4.4                2.9                 1.4   
9                 4.9                3.1                 1.5   

   petal width in cm        class  
0                0.2  Iris-setosa  
1                0.2  Iris-setosa  
2                0.2  Iris-setosa  
3                0.2  Iris-setosa  
4                0.2  Iris-setosa  
5                0.4  Iris-setosa  
6                0.3  Iris-setosa  
7                0.2  Iris-setosa  
8                0.2  Iris-setosa  
9                0.1  Iris-setosa

In [11]:
X=df.drop('class',axis=1)
X.head()

sepal length in cm  sepal width in cm  petal length in cm  \
0                 4.9                3.0                 1.4   
1                 4.7                3.2                 1.3   
2                 4.6                3.1                 1.5   
3                 5.0                3.6                 1.4   
4                 5.4                3.9                 1.7   

   petal width in cm  
0                0.2  
1                0.2  
2                0.2  
3                0.2  
4                0.4

In [13]:
y=df['class']
y.head(10)

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
5    Iris-setosa
6    Iris-setosa
7    Iris-setosa
8    Iris-setosa
9    Iris-setosa
Name: class, dtype: object

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [18]:
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [25]:
iris_ML = LogisticRegression(random_state=0)
iris_ML.fit(X_train, y_train)

pred_iris_ML = iris_ML.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_iris_ML))
print (confusion_matrix(y_test, pred_iris_ML))


--- Logistic Regression Classifier ---
0.8947368421052632
[[14  0  0]
 [ 0 13  1]
 [ 0  3  7]]


C:\Users\7kingdom\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


위에 처럼 오류가 발생한다. 한 번 해결해보자,


  ChatGPT에게 물어보니 Logistic Regression 모델의 lbfgs 최적화 알고리즘을 사용하는데 이게 최대 반복 횟수까지 도달해서 발생하는 문제였다.
  
  해결방법
  
  1. max_iter을 증가시킨다.<br>
      iris_ML = LogisticRegression(random_state=0, max_iter=1000)  # 예시로 1000으로 증가시킴<br><br>
  2. 다른 최적화 알고리즘을 사용한다.<br>
      알고리즘 관련 매개변수는 solver인데 이를 newton-cg을 사용하든 sag를 사용하든 다른 걸 한 번 써본다.<br>
      iris_ML = LogisticRegression(random_state=0, solver='sag')

  

In [27]:
iris_ML = LogisticRegression(random_state=0, max_iter=1000)
iris_ML.fit(X_train, y_train)

pred_iris_ML = iris_ML.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_iris_ML))
print (confusion_matrix(y_test, pred_iris_ML))


--- Logistic Regression Classifier ---
0.8947368421052632
[[14  0  0]
 [ 0 13  1]
 [ 0  3  7]]


---
나눈 데이터 한 번 보기
--
X_train, y_train, X_test, y_test

In [20]:
X_train

sepal length in cm  sepal width in cm  petal length in cm  \
51                  6.9                3.1                 4.9   
2                   4.6                3.1                 1.5   
146                 6.5                3.0                 5.2   
10                  4.8                3.4                 1.6   
56                  4.9                2.4                 3.3   
..                  ...                ...                 ...   
9                   5.4                3.7                 1.5   
103                 6.5                3.0                 5.8   
67                  6.2                2.2                 4.5   
117                 7.7                2.6                 6.9   
47                  5.3                3.7                 1.5   

     petal width in cm  
51                 1.5  
2                  0.2  
146                2.0  
10                 0.2  
56                 1.0  
..                 ...  
9                  0.2  
103                2.2  
67                 1.5  
117                2.3  
47                 0.2  

[111 rows x 4 columns]

In [21]:
y_train

51     Iris-versicolor
2          Iris-setosa
146     Iris-virginica
10         Iris-setosa
56     Iris-versicolor
            ...       
9          Iris-setosa
103     Iris-virginica
67     Iris-versicolor
117     Iris-virginica
47         Iris-setosa
Name: class, Length: 111, dtype: object

In [22]:
X_test

sepal length in cm  sepal width in cm  petal length in cm  \
133                 6.1                2.6                 5.6   
109                 6.5                3.2                 5.1   
59                  5.0                2.0                 3.5   
80                  5.5                2.4                 3.7   
7                   4.4                2.9                 1.4   
104                 7.6                3.0                 6.6   
140                 6.9                3.1                 5.1   
95                  5.7                2.9                 4.2   
118                 6.0                2.2                 5.0   
84                  6.0                3.4                 4.5   
33                  4.9                3.1                 1.5   
44                  4.8                3.0                 1.4   
54                  5.7                2.8                 4.5   
24                  5.0                3.0                 1.6   
37                  4.4                3.0                 1.3   
132                 6.3                2.8                 5.1   
111                 6.8                3.0                 5.5   
73                  6.4                2.9                 4.3   
16                  5.1                3.5                 1.4   
45                  5.1                3.8                 1.6   
40                  4.5                2.3                 1.3   
8                   4.9                3.1                 1.5   
85                  6.7                3.1                 4.7   
22                  5.1                3.3                 1.7   
62                  6.1                2.9                 4.7   
94                  5.7                3.0                 4.2   
90                  6.1                3.0                 4.6   
26                  5.2                3.5                 1.5   
43                  5.1                3.8                 1.9   
134                 7.7                3.0                 6.1   
27                  5.2                3.4                 1.4   
97                  5.1                2.5                 3.0   
96                  6.2                2.9                 4.3   
69                  5.9                3.2                 4.8   
18                  5.1                3.8                 1.5   
105                 4.9                2.5                 4.5   
136                 6.4                3.1                 5.5   
61                  6.0                2.2                 4.0   

     petal width in cm  
133                1.4  
109                2.0  
59                 1.0  
80                 1.0  
7                  0.2  
104                2.1  
140                2.3  
95                 1.3  
118                1.5  
84                 1.6  
33                 0.1  
44                 0.3  
54                 1.3  
24                 0.2  
37                 0.2  
132                1.5  
111                2.1  
73                 1.3  
16                 0.3  
45                 0.2  
40                 0.3  
8                  0.1  
85                 1.5  
22                 0.5  
62                 1.4  
94                 1.2  
90                 1.4  
26                 0.2  
43                 0.4  
134                2.3  
27                 0.2  
97                 1.1  
96                 1.3  
69                 1.8  
18                 0.3  
105                1.7  
136                1.8  
61                 1.0

In [23]:
y_test

133     Iris-virginica
109     Iris-virginica
59     Iris-versicolor
80     Iris-versicolor
7          Iris-setosa
104     Iris-virginica
140     Iris-virginica
95     Iris-versicolor
118     Iris-virginica
84     Iris-versicolor
33         Iris-setosa
44         Iris-setosa
54     Iris-versicolor
24         Iris-setosa
37         Iris-setosa
132     Iris-virginica
111     Iris-virginica
73     Iris-versicolor
16         Iris-setosa
45         Iris-setosa
40         Iris-setosa
8          Iris-setosa
85     Iris-versicolor
22         Iris-setosa
62     Iris-versicolor
94     Iris-versicolor
90     Iris-versicolor
26         Iris-setosa
43         Iris-setosa
134     Iris-virginica
27         Iris-setosa
97     Iris-versicolor
96     Iris-versicolor
69     Iris-versicolor
18         Iris-setosa
105     Iris-virginica
136     Iris-virginica
61     Iris-versicolor
Name: class, dtype: object